#!/bin/sh

animation=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$animation" = 1 ]; then
	hyprctl --batch "\
		keyword animations:enabled 0;\
		keyword animation borderangle,0;\
		keyword decoration:shadow:enabled 0;\
		keyword decoration:blur:enabled 0;\
		keyword decoration:active_opacity 1;\
		keyword decoration:inactive_opacity 1;"
	brightnessctl -s set 40%
	notify-send -u low --app-name="power control" "Powersaving on" "Decorations and animations have been disabled."
else
	hyprctl reload
	brightnessctl -r
	notify-send -u low --app-name="power control" "Powersaving off" "Configuration has been reloaded to default."
fi
