#!/bin/sh

DOTPATH=~/.dotfiles
FLAGPATH=~/.dotfiles/flaglist.sh
PKGLIST=~/.dotfiles/pkglist.txt
YAYPKGLIST=~/.dotfiles/foreignpkglist.txt

source $FLAGPATH

confirm() {					# usage: confirm "Prompt" optional: -N
local response
local defaultresponse="Y"
local responsebox="[Y/n]"

if [ "$2" = "-N" ]; then
	responsebox="[y/N]"
	defaultresponse="N"
fi

while true; do
	read -rp "$1 $responsebox" response
	response="${response:-$defaultresponse}"
	case "$response" in
		[Yy]* )
			return 0
			;;
		[Nn]* )
			return 1
			;;
		* )
			echo "Invalid input."
			;;
	esac
done
}

execute(){
$1
local exitcode="$?"

if [ "$2" = "-debug" ]; then
	exitcode="0"
fi

if [ "$exitcode" = "0" ]; then
	return 0
else
	return $exitcode
fi
}

show_progress() {
	echo "Progress:"
	cat $FLAGPATH
	echo "It is strongly recommended to run this script in a separate tty to prevent any unexpected behaviour."
	confirm "Proceed with installation?"
	case "$?" in
		0 )
			return 0;;
		1 )
			echo "Exiting installer..."
			exit;;
	esac
}

pacman_install() {
	echo "Installing all recommended packages..."
	echo 
	execute "sudo pacman -Sy" || { echo "Failed to update pacman db. Exit code: $?"; exit 1 }
	execute "sudo pacman -S --needed - < $PKGLIST" || { echo "Failed to install packages. Exit code: $?"; exit 2 }
	sed -i 's/PACMAN="0"/PACMAN="1"/' $FLAGPATH
	return
}

setup_yay() {
	confirm "Has yay been installed on this device?" -N
	case $? in
		0 ) 
			break;;
		1 ) 
			printf "\nSetting up yay\n"
			execute "git clone https://aur.archlinux.org/yay.git" || { echo "Failed to clone yay repository. Exit code: $?"; exit 3 }
			cd ~/yay
			execute "makepkg -si" || { echo "Failed to build yay. Exit code: $?"; exit 4 }
			cd ~
			sed -i 's/YAYSETUP="0"/YAYSETUP="1"/' $FLAGPATH
			printf "\nyay set up.\n"
			break;;
	esac
	return
}

yay_install() {
	echo "Installing yay packages..."
	execute "yay -Y --gendb" || { echo "Failed to generate development package database. Exit code: $?"; exit 5 }
	execute "yay -Syu --devel" || { echo "Failed to update development packages. Exit code: $?"; exit 6 }
	execute "yay -S - < $YAYPKGLIST" || { echo "Failed to install required AUR packages. Exit code: $?"; exit 7 }
	sed -i 's/YAYIN="0"/YAYIN="1"/' $FLAGPATH
	printf "\nAUR packages installed.\n"
	return
}

config_change() {
	confirm "Proceed with changing configs?"
	case $? in
		0 )
			break;;
		1 )
			return;;
	esac
	SUFFIX="-pre-sakoora"
	printf "\nRenaming preexisting config files\n"
	if [[ -d ~/.config/hypr ]]; then
		mv ~/.config/hypr ~/.config/hypr$SUFFIX
	fi
	if [[ -d ~/.config/dunst ]]; then
		mv ~/.config/dunst ~/.config/dunst$SUFFIX
	fi
	if [[ -d ~/.config/fastfetch ]]; then
		mv ~/.config/fastfetch ~/.config/fastfetch$SUFFIX
	fi
	if [[ -d ~/.config/kitty ]]; then
		mv ~/.config/kitty ~/.config/kitty$SUFFIX
	fi
	if [[ -d ~/.config/waybar ]]; then
		mv ~/.config/waybar ~/.config/waybar$SUFFIX
	fi
	if [[ -d ~/.config/rofi ]]; then
		mv ~/.config/rofi ~/.config/rofi$SUFFIX
	fi
	if [[ -d ~/.config/scripts ]]; then
		mv ~/.config/scripts ~/config/scripts$SUFFIX
	fi
	printf "\nOld config files have been renamed to [config_folder]-pre-sakoora.\n"
	sleep 0.5
	printf "\nMoving config files from .dotfiles to required location"
	mv $DOTPATH/.config/hypr ~/.config/
	mv $DOTPATH/.config/dunst ~/.config/
	mv $DOTPATH/.config/fastfetch ~/.config/
	mv $DOTPATH/.config/kitty ~/.config/
	mv $DOTPATH/.config/waybar ~/.config/
	mv $DOTPATH/.config/rofi ~/.config/
	mv $DOTPATH/.config/scripts ~/.config/
	sleep 0.5
	printf "\nMoving wallpapers"
	if [[ -d ~/Pictures ]]; then
		printf "\nPictures directory already exists...\n"
	else
		mkdir ~/Pictures
	fi
	if [[ -d ~/Pictures/Wallpapers ]]; then
		printf "\nWallpapers directory already exists...\n"
		mv $DOTPATH/Wallpapers/* ~/Pictures/Wallpapers/
	else
		mkdir ~/Pictures/Wallpapers
		mv $DOTPATH/Wallpapers ~/Pictures
	fi
	printf "\nSet a wallpaper using wallset command in terminal. wallset runs\n pywal which is needed for waybar to load."
	sleep 0.5
	printf "\nMoving required font files to ~/.local/share/fonts/\n"
	if [[ -d ~/.local/share/fonts ]]; then
		printf "\nFonts directory already exists...\n"
		mv $DOTPATH/fonts/* ~/.local/share/fonts/
	elif [[ -d ~/.local/share ]]; then
		mv $DOTPATH/fonts ~/.local/share/
	else
		mkdir ~/.local/share
		mv $DOTPATH/fonts ~/.local/share/
	fi
	sed -i 's/CONFIG="0"/CONFIG="1"/' $FLAGPATH
	return
}

main() {
show_progress
[ "$PACMAN" = "0" ] && \
	pacman_install
[ "$YAYSETUP" = "0" ] && \
	setup_yay
[ "$YAYIN" = "0" ] && \
	yay_install
[ "$CONFIG" = "0" ] && \
	config_change
echo "Installation complete!"
exit
}

cd ~
clear
cat <<"EOF"
            _                              _       _       
           | |                            | |     | |      
  ___  __ _| | _____   ___  _ __ __ _   __| | ___ | |_ ___ 
 / __|/ _` | |/ / _ \ / _ \| '__/ _` | / _` |/ _ \| __/ __|
 \__ \ (_| |   < (_) | (_) | | | (_| || (_| | (_) | |_\__ \
 |___/\__,_|_|\_\___/ \___/|_|  \__,_(_)__,_|\___/ \__|___/
                                                           
                                                           
EOF

main
