#!/bin/bash

DOTPATH=~/.dotfiles
FLAGPATH=~/.dotfiles/flaglist.sh
PKGLIST=~/.dotfiles/pkglist.txt
YAYPKGLIST=~/.dotfiles/foreignpkglist.txt

source $FLAGPATH

cd ~
clear
cat <<"EOF"
            _                              _       _       
           | |                            | |     | |      
  ___  __ _| | _____   ___  _ __ __ _   __| | ___ | |_ ___ 
 / __|/ _` | |/ / _ \ / _ \| '__/ _` | / _` |/ _ \| __/ __|
 \__ \ (_| |   < (_) | (_) | | | (_| || (_| | (_) | |_\__ \
 |___/\__,_|_|\_\___/ \___/|_|  \__,_(_)__,_|\___/ \__|___/
                                                           
                                                           
EOF
# 0.5. Display current status according to flags
printf "\nProgress:\n"
cat $FLAGPATH
sleep 3
printf "\nIt is strongly recommended to run this script in a separate tty to prevent any unexpected behaviour\n"
while true; do
    read -p "Proceed with installation? [y/n]" installyn
    case $installyn in
        [Yy]* ) break;;
        [Nn]* ) exit;; 
        * ) echo "Input y/n.";;
    esac
done

# 1. Install pacman packages
if [[ $PACMAN == 0 ]]; then
	printf "\nInstalling all recommended packages\n"
	sudo pacman -Sy
	if [[ $? -gt 0 ]]; then
		printf "\nPacman sync failed, exiting installer."
		exit
	fi
	sleep 0.5
	sudo pacman -S --needed - < $PKGLIST
	if [[ $? -eq 0 ]]; then
		sed -i 's/PACMAN="0"/PACMAN="1"/' $FLAGPATH
		printf "\nPackages installed.\n"
	else
		printf "\nPackages were not installed.\n"
		exit
	fi
else
	printf "\nRequired packages have already been installed.\n"
fi
sleep 3

# 2. Setup yay
if [[ $YAYSETUP == 0 ]]; then
	while true; do
    		read -p "Has yay been installed on this device? [y/n]" installyn
    		case $installyn in
        		[Yy]* ) break;;
        		[Nn]* ) printf "\nSetting up yay\n"
				git clone https://aur.archlinux.org/yay.git
				if [[ $? -gt 0 ]]; then
					printf "\nCloning into yay repository failed, exiting installer."
					exit
				fi
				cd ~/yay
				sleep 0.5
				makepkg -si
				sleep 0.5
				cd ~
				sed -i 's/YAYSETUP="0"/YAYSETUP="1"/' $FLAGPATH
				printf "\nyay set up.\n"
				break;;
        		* ) echo "Input y/n.";;
   		esac
	done
else
	printf "\nyay has been previously set up.\n"
fi
sleep 3

# 3. Install yay packages
if [[ $YAYIN == 0 ]]; then
	printf "\nInstalling AUR packages via yay\n"
	yay -Y --gendb
	sleep 0.5
	yay -Syu --devel
	sleep 0.5
	yay -S - < $YAYPKGLIST
	if [[ $? -gt 0 ]]; then
		printf "\nInstallation of AUR packages failed.\n"
		exit
	fi
	sed -i 's/YAYIN="0"/YAYIN="1"/' $FLAGPATH
	printf "\nAUR packages installed.\n"
else
	printf "\nAUR packages have already been installed.\n"
fi
sleep 3

# 4. zsh configuration.
if [[ $ZSHDEF == 0 ]]; then
	printf "\nInstalling oh-my-zsh\n"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
	sleep 0.5
	cat ~/.dotfiles/.zshalias >> ~/.zshrc
	sudo chsh -s /usr/bin/zsh $USER
	sed -i 's/ZSHDEF="0"/ZSHDEF="1"/' $FLAGPATH
	printf "\nzsh set up.\n"
else
	printf "\nzsh had already been set up.\n"
fi
sleep 3

# 5. Configs
if [[ $CONFIG == 0 ]]; then
	while true; do
    		read -p "Proceed with changing configs? [y/n]" configyn
    		case $configyn in
        		[Yy]* ) break;;
        		[Nn]* ) exit;; 
        		* ) echo "Input y/n.";;
    		esac
	done
	SUFFIX="-pre-sakoora"
	printf "\nRenaming preexisting config files\n"
	if [[ -d ~/.config/hypr ]]; then
		mv ~/.config/hypr ~/.config/hypr$SUFFIX
	fi
	if [[ -d ~/.config/dunst ]]; then
		mv ~/.config/dunst ~/.config/dunst$SUFFIX
	fi
	if [[ -d ~/.config/fastfetch ]]; then
		mv ~/.config/fastfetch ~/.config/fastfetch$SUFFIX
	fi
	if [[ -d ~/.config/kitty ]]; then
		mv ~/.config/kitty ~/.config/kitty$SUFFIX
	fi
	if [[ -d ~/.config/waybar ]]; then
		mv ~/.config/waybar ~/.config/waybar$SUFFIX
	fi
	if [[ -d ~/.config/rofi ]]; then
		mv ~/.config/rofi ~/.config/rofi$SUFFIX
	fi
	if [[ -d ~/.config/scripts ]]; then
		mv ~/.config/scripts ~/config/scripts$SUFFIX
	fi
	printf "\nOld config files have been renamed to [config_folder]-pre-sakoora.\n"
	sleep 0.5
	printf "\nMoving config files from .dotfiles to required location"
	mv $DOTPATH/.config/hypr ~/.config/
	mv $DOTPATH/.config/dunst ~/.config/
	mv $DOTPATH/.config/fastfetch ~/.config/
	mv $DOTPATH/.config/kitty ~/.config/
	mv $DOTPATH/.config/waybar ~/.config/
	mv $DOTPATH/.config/rofi ~/.config/
	mv $DOTPATH/.config/scripts ~/.config/
	sleep 0.5
	printf "\nMoving wallpapers"
	if [[ -d ~/Pictures ]]; then
		printf "\nPictures directory already exists...\n"
	else
		mkdir ~/Pictures
	fi
	if [[ -d ~/Pictures/Wallpapers ]]; then
		printf "\nWallpapers directory already exists...\n"
		mv $DOTPATH/Wallpapers/* ~/Pictures/Wallpapers/
	else
		mkdir ~/Pictures/Wallpapers
		mv $DOTPATH/Wallpapers ~/Pictures
	fi
	printf "\nSet a wallpaper using wallset command in terminal. wallset runs\n pywal which is needed for waybar to load."
	sleep 0.5
	printf "\nMoving required font files to ~/.local/share/fonts/\n"
	if [[ -d ~/.local/share/fonts ]]; then
		printf "\nFonts directory already exists...\n"
		mv $DOTPATH/fonts/* ~/.local/share/fonts/
	elif [[ -d ~/.local/share ]]; then
		mv $DOTPATH/fonts ~/.local/share/
	else
		mkdir ~/.local/share
		mv $DOTPATH/fonts ~/.local/share/
	fi
	sed -i 's/CONFIG="0"/CONFIG="1"/' $FLAGPATH
else
	printf "\nConfiguration is already completed.\n"
fi
sleep 3

# 6. App defaults
if [[ $APPDEF == 0 ]]; then
	printf "\nSetting up app defaults for dolphin"
	sudo update-desktop-database
	sleep 0.5
	if [[ -f /etc/xdg/menus/arch-applications.menu ]]; then
		cd /etc/xdg/menus
		sudo mv arch-applications.menu applications.menu
		cd ~
	fi
	if [[ -f /etc/xdg/menus/applications.menu ]]; then
		kbuildsycoca6 --noincremental
		sed -i 's/APPDEF="0"/APPDEF="1"/' $FLAGPATH
		printf "\nSystem configured.\n"
	else
		printf "\nPlease check if archlinux-xdg-menu is installed, then rerun install script.\nIf it is installed and this still doesn't work, report it.\n"
	fi
else
	printf "\nDefaults already setup.\n"
fi

printf "\nIt is recommended to reboot your system and log into hyprland (uwsm-managed) through sddm now.\n"
while true; do
    		read -p "Would you like to continue the installation [y/n]" rebootyn
    		case $rebootyn in
        		[Yy]* ) break;;
        		[Nn]* ) echo "You can always continue the installation where you left off by running the script again."
				exit;;
        		* ) echo "Input y/n.";;
    		esac
done

# 7. Hyprcursor
if [[ $HYPRCURSOR == 0 ]]; then
	printf "\nDynamic cursor installation requires you to be logged into a hyprland session.\n"
	if hyprctl monitors > /dev/null 2>&1; then
	while true; do
    		read -p "Install dynamic cursor? [y/n]" cursoryn
    		case $cursoryn in
        		[Yy]* ) hyprpm update
				if [[ $? -gt 0 ]]; then
					printf "\nHyprpm setup failed. Check your internet connection and try again.\n"
					exit
				fi
				hyprpm add https://github.com/virtcode/hypr-dynamic-cursors
				hyprpm enable dynamic-cursors
				if [[ $? -gt 0 ]]; then
					printf "\nInstallation of dynamic cursor failed. Have you logged into hyprland?\nExiting...\n"
					exit
				fi
				sed -i 's/HYPRCURSOR="0"/HYPRCURSOR="1"/' $FLAGPATH
				printf "\nTo disable the dynamic cursor, simply run\nhyprpm disable dynamic-cursors.\nDynamic cursor is set to tilt, to adjust it,\nedit config file in .config/hypr/configs/cursor.conf\n"
				break;;
        		[Nn]* ) break;; 
        		* ) echo "Input y/n.";;
    		esac
	done
	else
		echo "Hyprland is not running. Dynamic cursor cannot be installed."
	fi
fi
printf "\nReached the end of the installation!\n"
exit
