#!/usr/bin/env bash

dotpath="$HOME"/.dotfiles
flagpath="$HOME"/.dotfiles/flaglist.sh
pkglist="$HOME"/.dotfiles/pkglist.txt
yaypkglist="$HOME"/.dotfiles/foreignpkglist.txt
configfolder="$HOME"/.config

modifiedconfigs=("/hypr" "/mako" "/fastfetch" "/kitty" "/waybar" "/rofi" "/scripts" "/starship.toml" "/wal")

source "$flagpath"

s_noyay="0"
alertsign="[ \033[1m!\033[0m ]"
checksign="[ ✔ ]"
crosssign="[ ✖ ]"
infosign="[ \033[1mi\033[0m ]"
questionsign="[ \033[1m?\033[0m ]"

case "$1" in
	"-noyay" ) 
		s_noyay="1";;
esac

bigtext() {
cat <<"EOF"
            _                              _       _       
           | |                            | |     | |      
  ___  __ _| | _____   ___  _ __ __ _   __| | ___ | |_ ___ 
 / __|/ _` | |/ / _ \ / _ \| '__/ _` | / _` |/ _ \| __/ __|
 \__ \ (_| |   < (_) | (_) | | | (_| || (_| | (_) | |_\__ \
 |___/\__,_|_|\_\___/ \___/|_|  \__,_(_)__,_|\___/ \__|___/
                                                           
                                                           
EOF
}

confirm() {
local response
local defaultresponse="Y"
local responsebox="[Y/n]"

if [ "$2" = "-N" ]; then
	responsebox="[y/N]"
	defaultresponse="N"
fi

while true; do
	echo -en "$questionsign $1 $responsebox "; read -r response
	response="${response:-$defaultresponse}"
	case "$response" in
		[Yy]* )
			return 0;;
		[Nn]* )
			return 1;;
		* )
			echo "Invalid input.";;
	esac
done
}

execute() {
"$@" |& tee "$logfile"
exitcode=${PIPESTATUS[0]}
return "$exitcode"
}

command_fail() {
case "$1" in
	1 )
		echo -e "$alertsign Failed to update pacman db. Pacman exit code: $exitcode";;
	2 )
		echo -e "$alertsign Failed to install pacman packages. Pacman exit code: $exitcode";;
	3 )
		echo -e "$alertsign Failed to clone yay repository. Git exit code: $exitcode";;
	4 )
		echo -e "$alertsign Failed to build yay. Makepkg exit code: $exitcode";;
	5 )
		echo -e "$alertsign Failed to generate development package database. Yay exit code: $exitcode";;
	6 )
		echo -e "$alertsign Failed to update development packages. Yay exit code: $exitcode";;
	7 )
		echo -e "$alertsign Failed to install required AUR packages. Yay exit code: $exitcode";;
	8 )
		echo -e "$infosign Exiting installer on user prompt [Pre-installation exit: 8]"
		exit 8;;
	9 )
		echo -e "$infosign Exiting installer on user prompt [Yay setup aborted: 9]"
		exit 9;;
	10 )
		echo -e "$infosign Exiting installer on user prompt [Configuration swap aborted: 10]"
		exit 10;;
	11 )
		echo -e "$alertsign Failed to change default login shell to zsh. Chsh exit code: $exitcode";;
	12 )
		echo -e "$alertsign Failed to clone zsh-syntax-highlighting repository. Git exit code: $exitcode";;
	13 )
		echo -e "$alertsign Failed to clone zsh-autosuggestions repository. Git exit code: $exitcode";;
	14 )
		echo -e "$alertsign Failed to clone zsh-history-substring-search repository. Git exit code: $exitcode";;
	15 )
		echo -e "$alertsign Hyprland is not running on current tty, launch Hyprland to continue. [Hyprland not running: 15]"
		exit 15;;
esac
echo "Failed command logged in file located at \"$logfile\""
echo "Installation failed with status: $1"
exit "$1"
}

test_tty() {
tty | grep -sq tty && s_intty="0" || s_intty="1"
return
}

command_exists() {
command -v "$@" >/dev/null 2>&1
}

append_suffix() {
if [ -d "$1" ]; then
	mv "$1" "$1$2"
fi
}

show_progress() {
	echo "Progress:"
	echo
	if [ "$s_pacman" = "0" ]; then
		echo "$crosssign Required pacman packages have not been installed yet."
	else
		echo "$checksign Required pacman packages installed."
	fi
	if [ "$s_noyay" = "0" ]; then
		if [ "$s_yay" = "0" ]; then
			echo "$crosssign Required AUR packages have not been installed yet."
		else
			echo "$checksign Required AUR packages installed."
		fi
	fi

	if [ "$s_zsh" = "0" ]; then
		echo "$crosssign Zsh has not been configured yet."
	else
		echo "$checksign Zsh configured."
	fi

	if [ "$s_config" = "0" ]; then
		echo "$crosssign Config files have not been replaced yet."
	else
		echo "$checksign Config files replaced."
	fi

	if [ "$s_hyprlock" = "0" ]; then
		echo "$crosssign Hyprlock has not been set up for your screen resolution."
	else
		echo "$checksign Hyprlock set up."
	fi

	if [ "$s_walls" = "0" ]; then
		echo -e "$infosign Wallpapers available."
	fi
	echo
	test_tty
	if [ "$s_intty" = "1" ]; then
		echo -e "$infosign It is detected that you're currently not on a tty! It is recommended to run this script in a tty to avoid any potential issues."
	fi
	if [ "$s_noyay" = "1" ]; then
		echo -e "$infosign -noyay flag was used. Install required AUR packages (located at $yaypkglist) in your preferred way."
	fi

	if [ "$s_intty" = "0" ]; then
		confirm "Proceed with installation?" 
	else
		confirm "Proceed with installation? (Not recommended)" -N
	fi
	case "$?" in
		0 )
			return;;
		1 )
			command_fail 8;;
	esac
}

pacman_install() {
	echo "Installing all required packages..."
	echo 
	execute sudo pacman -Syu --noconfirm || command_fail 1
	execute sudo pacman -S --needed --noconfirm - < "$pkglist" || command_fail 2
	sed -i 's/s_pacman="0"/s_pacman="1"/' "$flagpath"
	return
}

setup_yay() {
	echo "The next part of the installation requires yay, which has not been detected on your system."
	confirm "Do you want to install yay now?"
	case $? in
		0 ) 
			;;
		1 ) 
			echo -e "$infosign If you wish to skip installing yay (because you use a different AUR helper or otherwise), use -noyay flag when launching the installer."
			command_fail 9;;
	esac
	echo "Setting up yay..."
	execute git clone https://aur.archlinux.org/yay.git || command_fail 3
	cd "$HOME"/yay
	execute makepkg -si || command_fail 4
	cd "$HOME"
	echo "Yay has been installed."
	return
}

yay_install() {
	echo "Installing yay packages..."
	execute yay -Y --gendb --noconfirm || command_fail 5
	execute yay -Syu --devel --noconfirm || command_fail 6
	execute yay -S --needed --noconfirm - < "$yaypkglist" || command_fail 7
	sed -i 's/s_yay="0"/s_yay="1"/' "$flagpath"
	echo "AUR packages installed."
	return
}

setup_zsh() {
	local zshdir="$HOME/.zsh"
	echo "$SHELL" | grep -sq zsh
	if [ "$?" = "1" ]; then
		echo "Changing login shell to zsh..."
		execute sudo chsh -s /usr/bin/zsh "$USER" || command_fail 11
	else
		echo "Login shell already set to zsh."
	fi

	append_suffix "$zshdir" "-pre-sakoora"
	mkdir "$zshdir"
	execute git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$zshdir"/zsh-syntax-highlighting || command_fail 12
	execute git clone https://github.com/zsh-users/zsh-autosuggestions "$zshdir"/zsh-autosuggestions || command_fail 13
	execute git clone https://github.com/zsh-users/zsh-history-substring-search "$zshdir"/zsh-history-substring-search || command_fail 14

	append_suffix "$HOME"/.zshrc "-pre-sakoora"
	mv "$dotpath"/.zshrc "$HOME"/.zshrc

	sed -i 's/s_zsh="0"/s_zsh="1"/' "$flagpath"
	return
}

config_change() {
	confirm "Proceed with changing configs?"
	case $? in
		0 )
			;;
		1 )
			command_fail 10;;
	esac

	echo "Renaming preexisting config files..."
	local file
	for file in "${modifiedconfigs[@]}"; do
		append_suffix "$configfolder/$file" "-pre-sakoora"
	done
	echo "Old config files have been renamed to [config_folder]-pre-sakoora."

	echo "Moving config files from .dotfiles to required location..."
	mv "$dotpath"/.config/* "$configfolder"/
	echo "Done!"

	echo "Moving required font files to ~/.local/share/fonts/"
	mkdir -p "$HOME"/.local/share/fonts
	mv "$dotpath"/fonts/* "$HOME"/.local/share/fonts
	echo "Moved!"
	sed -i 's/s_config="0"/s_config="1"/' "$flagpath"
	return
}

hyprlock() {
	printenv HYPRLAND_INSTANCE_SIGNATURE &> /dev/null || command_fail 15

	sizefile="$HOME"/.config/hypr/sizes-hyprlock.sh
	sizefileconf="$HOME"/.config/hypr/sizes-hyprlock.conf
	[ -f "$sizefile" ] && rm "$sizefile"
	touch "$sizefile"
	[ -f "$sizefileconf" ] && rm "$sizefileconf"
	touch "$sizefileconf"
	echo "Setting up hyprlock for your display resolution."

	resolution=$(wlr-randr | grep "current" | awk '{print $1}')		# Check if hyprland is running or not before this
	width=$(echo "$resolution" | cut -dx -f1)
	height=$(echo "$resolution" | cut -dx -f2)
	[ $((4*height/9)) -ge $((width/4)) ] && pw=$((width/4)) || pw=$((4*height/9))
	pp=$((pw/12))
	{
		echo "#################"
		echo "### UNIVERSAL ###"
		echo "#################"
		echo "\$body_font = $((pp/2))"
		echo "\$huge_font = $((pp*5/2))"
		echo "\$heading_font = $((pp*5/4))"
		echo "\$large_font = $((pp*3/4))"
		echo "\$small_font = $((pp*3/8))"

		echo "################"
		echo "### TOP LEFT ###"
		echo "################"
		echo "\$top_left_offset = $((-pw/2-pp/2)), $((pw/4+pp/2))"
		echo "\$pw_box_offset = $((-pw/2-pp/2)), $((height/2-pp*3/2))"
		echo "\$un_box_offset = $((-pw/2-pp/2)), $((height/2+pp*3/2))"
		echo "\$pw_text_offset = $((width/2-pw+pp)), $((height/2))"
		echo "\$un_text_offset = $((width/2-pw+pp)), $((height/2+pp*3))"
		echo "\$login_text_offset = $((-pw/2-pp/2)), $((height/2+pp*5))"
		echo "\$hostname_text_offset = $((-pw/2-pp/2)), $((height/2+pp*15/2))"
		echo "\$un_value_offset = $((width/2-pw+pp)), $((height/2+pp*9/4))"
		echo "\$input_field_offset = $((width/2-pw+pp/2)), $((height/2-pp*3/2))"
		echo "\$top_left_size = $pw"
		echo "\$container_box_size = $((pw-pp*2)), $((pp*5/2))"
		echo "\$input_field_size = $((pw-pp*2)), $((pp*2))"

		echo "###################"
		echo "### BOTTOM LEFT ###"
		echo "###################"
		echo "\$bottom_left_offset = $((-pw/2-pp/2)), $((-pw/2-pp/2))"
		echo "\$time_text_offset = $((-pw/2-pp/2)), $((-height/2-pw/4-pp*3/2))"
		echo "\$uptime_ltext_offset = $((width/2-pw+pp*5/2)), $((height/2-pw*3/4+pp/2))"
		echo "\$uptime_rtext_offset = $((-width/2-pp*7/2)), $((height/2-pw*3/4+pp/2))"
		echo "\$bottom_left_size = $((pw/2))"

		echo "#############"
		echo "### RIGHT ###"
		echo "#############"
		echo "\$right_offset = $((pw/2+pp/2)), 0"
		echo "\$right_bottom_box_offset = $((pw/2+pp/2)), $((height/2-pw))"
		echo "\$network_box_offset = $((pw*3/16+pp*3/2)), $((height/2-pw*5/8+pp*2))"
		echo "\$bluetooth_box_offset = $((pw*9/16+pp*5/2)), $((height/2-pw*5/8+pp*2))"
		echo "\$power_box_offset = $((pw/2+pp/2)), $((height/2-pw+pp))"
		echo "\$image_offset = $((pw/2+pp/2)), $((height/2+pw*1/8+pp*5))"
		echo "\$media_symbol_offset = $((pw/2+pp/2)), $((-height/2+pp/2))"
		echo "\$network_symbol_offset = $((pw*3/16+pp*3/2)), $((height/2-pw*5/8+pp*7/2))"
		echo "\$bluetooth_symbol_offset = $((pw*9/16+pp*5/2)), $((height/2-pw*5/8+pp*7/2))"
		echo "\$day_value_offset = $((pw/2+pp/2)), $((height/2+pw*1/8+pp*2))"
		echo "\$date_value_offset = $((pw/2+pp/2)), $((height/2+pw*1/8+pp))"
		echo "\$media_content_value_offset = $((pw/2+pp/2)), $((-height/2-pp/2))"
		echo "\$media_player_value_offset = $((pw/2+pp/2)), $((-height/2-pp*5/4))"
		echo "\$network_value_offset = $((pw*3/16+pp*3/2)), $((height/2-pw*5/8+pp*11/4))"
		echo "\$bluetooth_value_offset = $((pw*9/16+pp*5/2)), $((height/2-pw*5/8+pp*11/4))"
		echo "\$power_status_value_offset = $((pw/2+pp/2)), $((height/2-pw+pp*2))"
		echo "\$power_percent_value_offset = $((pw/2+pp/2)), $((height/2-pw+pp*5/2))"
		echo "\$power_indicator_value_offset = $((pw/2+pp/2)), $((height/2-pw+pp*4))"
		echo "\$right_size = $pw"
		echo "\$right_bottom_box_size = $pw, $((pw*9/8))"
		echo "\$power_box_size = $((pw-pp*2)), $((pw*3/8))"
		echo "\$connection_box_size = $((pw*3/8)), $((pw/4))"
		echo "\$image_size = $((pw/3))"
	} >> "$sizefileconf"
	{
		echo "initial_cutout_offset=$((width/2-pw))+$((height/2-pp/2-pw))"
		echo "top_left_offset=0+$((pw*1/3-pp/2))"
		echo "bottom_left_offset=0+$((pw*4/3-pp*3/2))"
		echo "right_offset=$((pw+pp))+0"
		echo "initial_cutout_size=$((pw*2+pp))x$((pw*2))"
		echo "top_left_size=$((pw))x$pw"
		echo "bottom_left_size=$((pw))x$((pw/2))"
		echo "right_size=$((pw))x$((pw*2))"
	} >> "$sizefile"
	sed -i 's/s_hyprlock="0"/s_hyprlock="1"/' "$flagpath"
	return
}

wallpapers() {
	confirm "Do you want wallpapers?"
	case "$?" in
		0 )
			;;
		1 )
			echo "wallset command requires any wallpapers to be located in $HOME/Pictures/Wallpapers/ for it to work."
			return;;
	esac
	git clone --single-branch --branch media https://github.com/pinkSakoora/.dotfiles.git "$dotpath"/walls
	mkdir -p "$HOME"/Pictures/Wallpapers
	mv "$dotpath"/walls/Wallpapers/* "$HOME"/Pictures/Wallpapers/
	echo "Wallpapers moved!"
	echo "Set a wallpaper using wallset command in terminal. wallset runs pywal which is needed for waybar to load."
	sed -i 's/s_walls="0"/s_walls="1"/' "$flagpath"
}

main() {
logfile="$HOME/.dotfiles/s_info$$.log"
touch "$logfile"
bigtext
show_progress
[ "$s_pacman" = "0" ] && \
	pacman_install
if [ "$s_noyay" = "0" ]; then
	if ! command_exists yay; then
		setup_yay
	fi
	[ "$s_yay" = "0" ] && \
		yay_install
fi
[ "$s_zsh" = "0" ] && \
	setup_zsh
[ "$s_config" = "0" ] && \
	config_change
[ "$s_hyprlock" = "0" ] && \
	hyprlock
[ "$s_walls" = "0" ] && \
	wallpapers
bigtext
echo "Installation complete!"
echo "Reboot your system and log into hyprland to enjoy your new config."
exit
}

cd "$HOME"
clear
main
