#!/bin/zsh

if [[ $(cat /sys/class/power_supply/BAT1/capacity) -gt 80 ]]; then
	echo "<span>  </span>"
elif [[ $(cat /sys/class/power_supply/BAT1/capacity) -gt 60 ]]; then
	echo "<span>  </span>"
elif [[ $(cat /sys/class/power_supply/BAT1/capacity) -gt 40 ]]; then
	echo "<span>  </span>"
elif [[ $(cat /sys/class/power_supply/BAT1/capacity) -gt 20 ]]; then
	echo "<span>  </span>"
else
	echo "<span>  </span>"
fi
