#!/bin/zsh

CACHE_DIR=~/.cache/hyprlock-cache
# Blur background
magick $CACHE_DIR/beforelock.png -scale 10% -blur 0x6.4 -resize 1000% $CACHE_DIR/blurbg.png

# Top panel
magick $CACHE_DIR/blurbg.png -crop 480x480+460+200 -modulate 60,90 $CACHE_DIR/lefttoppanel.png

# Bottom panel
magick $CACHE_DIR/blurbg.png -crop 480x160+460+720 -modulate 60,90 $CACHE_DIR/leftbottompanel.png
