#!/bin/zsh

if [ nmcli -t -f DEVICE,STATE con show --active | grep -q '^en*:' ]; then
    echo "<span>  </span>"
elif [ nmcli -t -f DEVICE,STATE con show --active | grep -q '^wl*:' ]; then
    echo "<span>  </span>"
else
    echo "<span>  </span>"
fi

