#!/bin/zsh

quote_file=~/.config/hypr/quotes.txt

if [[ ! -f "$quote_file" ]]; then
	echo "$quote_file not found"
	exit 1
fi

# Get the number of lines in the quote file
num_lines=$(wc -l < "$quote_file")

# Generate a random line number
random_line=$((RANDOM % num_lines + 1))

# Extract the random line and print it
quote=$(sed -n "${random_line}p" "$quote_file")
echo "<span font_style='italic'>$quote</span>"
