#!/bin/zsh

# Import pywal colors
COLORS=~/.cache/wal/colors.sh
source $COLORS
CACHE_DIR=~/.cache/hyprlock-cache

# Draw bottom panel
magick -size 480x840 xc:$background $CACHE_DIR/backpanel.png

# Draw linear gradient
magick -size 320x320 gradient:$color1-$color5 $CACHE_DIR/gradient.png

# Draw mask and use it to make the circle with linear gradient
magick -size 320x320 xc:none -draw 'circle 160,160 160,0' $CACHE_DIR/mask.png
magick $CACHE_DIR/gradient.png $CACHE_DIR/mask.png -alpha set -compose CopyOpacity -composite $CACHE_DIR/circle.png

# Append circle on top of bottom panel
magick $CACHE_DIR/backpanel.png $CACHE_DIR/circle.png -geometry +130+260 -composite $CACHE_DIR/panel_with_circle.png

# ^ Can be further optimised to just use one image instead of three but I'm lazy

# Draw top panel
magick -size 250x660 xc:none -fill $color1 -draw 'roundrectangle 0,0,249,659,50,50' -channel A -evaluate set 20% +channel $CACHE_DIR/toppanel.png

# Blur required portion of circle
magick $CACHE_DIR/panel_with_circle.png -crop 290x840+0+0 +repage -blur 0x24 $CACHE_DIR/blurredcircle.png
magick $CACHE_DIR/panel_with_circle.png $CACHE_DIR/blurredcircle.png -gravity west -composite $CACHE_DIR/finalbackpanel.png

# Composite top panel
magick $CACHE_DIR/finalbackpanel.png $CACHE_DIR/toppanel.png -geometry +40+90 -compose add -composite $CACHE_DIR/finalpanel.png
