#!/bin/sh

walldir="$HOME/Pictures/Wallpapers"

if [ ! -d "$walldir" ]; then
	printf "Wallpaper directory (%s) wasn't found!" "$walldir"
	exit 1
fi
selected_file=$(fd . "$walldir" | fzf --no-color --height=80% --min-height=6 --border=rounded --header="Select wallpaper" --header-first --with-nth 6 --delimiter /)
if [ ! -f "$selected_file" ]; then
	printf "Invalid filename: %s\n" "$selected_file"
	exit 2
fi
wal -i "$selected_file" -nq
swww img -t outer "$selected_file"
wallname=$(echo "$selected_file" | cut -d/ -f6)
printf "Setting %s as wallpaper.\n" "$wallname"
