windowrule = match:class .*, suppress_event maximize
windowrule {
	name = fix-xwayland-drag
	match:class = ^$
	match:title = ^$
	match:xwayland = true
	match:float = true
	match:fullscreen = false
	match:pin = false

	no_initial_focus = off
}

windowrule {
	name = dialog-fix
	match:class = ^()$
	match:title = ^()$

	no_blur = on
	opaque = on
}
# Kitty
windowrule {
	name = kitty-tweaks
	match:class = kitty

	float = on
	opacity = 0.83 0.7
	size = (monitor_w*0.5) (monitor_h*0.5)
	move = (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5))
}

layerrule {
	name = rofi-tweaks
	match:namespace = rofi

	blur = on
	ignore_alpha = 0
	animation = slide left
}

layerrule {
	name = waybar-tweaks
	match:namespace = waybar

	blur = on
	ignore_alpha = 0
}

layerrule {
	name = notifications-tweaks
	match:namespace = notifications

	blur = on
	ignore_alpha = 0
	animation = slide right
}
